# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5)           += cyttsp5/
obj-$(CONFIG_TOUCHSCREEN_RM_TS)                     += raydium/
obj-$(CONFIG_TOUCHSCREEN_FTS)                       += focaltech_touch/
obj-$(CONFIG_TOUCHSCREEN_ZTX)                       += zinitix/

